# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build PAF test base image

on:
  push:
    #branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile
  pull_request:
    #branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: ghcr.io/mreiche/paf-test-base:latest
#      credentials:
#        username: mreiche
#        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    #steps:
    # - uses: actions/checkout@v3
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.10"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          username: mreiche
#          password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-base.Dockerfile
          push: true
          tags: mreiche/paf-test-base:latest
