name: Build PAF test base image

on:
  push:
    branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-base.Dockerfile
          push: ${{ github.event.name == 'pull_request' && 'false' || 'true' }}
          tags: mreiche/paf-test-base:latest
