name: Build PAF test base image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mreiche/paf-test-base

on:
  push:
    branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile
      - .github/workflows/build-paf-test-base.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - ubuntu-base.Dockerfile
      - .github/workflows/build-paf-test-base.yml

permissions:
  contents: read

# https://github.com/marketplace/actions/build-and-push-docker-images
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ubuntu-base.Dockerfile
          push: ${{ github.event.name == 'pull_request' && 'false' || 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true
